name: Docker

on: [
    push,
    pull_request
]

jobs:
    docker-alpine-php-74-postgresql-functional:
        name: "Docker / Alpine / PHP 7.4 / PostgreSQL / Functional"
        runs-on: ubuntu-18.04
        env:
            PROGRESS_TYPE: plain
            SPRYKER_PLATFORM_IMAGE: spryker/php:7.4
            TRAVIS: 1

        steps:
            - uses: actions/checkout@v1
              with:
                  fetch-depth: 1

            - name: Install apt-packages
              run: |
                  sudo apt-get install apache2-utils

            - name: Run docker
              run: |
                  git clone https://github.com/spryker/docker-sdk.git --single-branch --branch master ./docker
                  docker/sdk boot deploy.ci.functional.yml -v
                  docker/sdk up -t -v
                  docker/sdk testing codecept run -c codeception.ci.functional.yml
