name: Marketplace

on: [
    push,
    pull_request
]

jobs:
    validation:
        runs-on: ubuntu-18.04
        strategy:
            fail-fast: false
            matrix:
                php-version: [
                    '7.3',
                    '7.4',
                    'nightly'
                ]

        env:
            APPLICATION_ENV: devtest
            APPLICATION_STORE: DE
            PROJECT: suite

        steps:
            - uses: actions/checkout@v1
              with:
                  fetch-depth: 1

            - uses: actions/setup-node@v1
              with:
                  node-version: '12'

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Get Composer Cache Directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"

            - uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Composer install
              run: |
                  composer --version
                  composer install

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, intl

            - name: Generate transfer objects
              run: vendor/bin/console transfer:generate

            - name: Install dependencies
              run: vendor/bin/console frontend:mp:install-dependencies

            - name: Build frontend
              run: vendor/bin/console frontend:mp:build

            - name: Test
              run: yarn mp:test
