name: Validation

on: [
    push,
    pull_request
]

jobs:
    validation:
        runs-on: ubuntu-18.04
        strategy:
            fail-fast: false
            matrix:
                php-version: [
#                    '7.3',
                    '7.4',
#                    'nightly'
                ]

        services:
            mariadb:
                image: mariadb:latest
                ports:
                    - 3306:3306
                env:
                    MYSQL_USER: devtest
                    MYSQL_PASSWORD: mate20mg
                    MYSQL_DATABASE: DE_devtest_zed
                    MYSQL_ROOT_PASSWORD: mate20mg
                options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

        env:
            APPLICATION_ENV: devtest
            APPLICATION_STORE: DE
            PROJECT: suite
            SPRYKER_TESTING_ENABLED: 1

        steps:
            - uses: actions/checkout@v1
              with:
                  fetch-depth: 1

            - name: Configure sysctl limits
              run: |
                sudo swapoff -a
                sudo sysctl -w vm.swappiness=1
                sudo sysctl -w fs.file-max=262144
                sudo sysctl -w vm.max_map_count=262144

            - uses: getong/elasticsearch-action@v1.2
              with:
                elasticsearch version: '7.6.1'
                host port: 9200
                container port: 9200
                host node port: 9300
                node port: 9300
                discovery type: 'single-node'

            - uses: actions/setup-node@v1
              with:
                  node-version: '12'

            - uses: ./.github/actions/composer

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, intl, pdo_mysql

            - name: Generate transfer objects
              run: vendor/bin/console transfer:generate

            - name: Generate transfer databuilder objects
              run: vendor/bin/console transfer:databuilder:generate

#            - name: Propel install
#              run: vendor/bin/console propel:install

            - name: Setup search
              run: vendor/bin/console setup:search

            - name: Install NPM packages
              run: |
                  npm install speccy@0.11.0 -g

            - name: Codecept build
              run: vendor/bin/codecept build --ansi

            - name: Generate autocompletion files
              run: vendor/bin/console dev:ide-auto-completion:generate

            - name: Generate rest API dcoumentation
              run: vendor/bin/console rest-api:generate:documentation

            - name: Frontend install-dependencies
              run: |
                vendor/bin/console frontend:project:install-dependencies
                vendor/bin/console frontend:yves:install-dependencies

            - name: Validate propel files
              run: |
                  vendor/bin/console propel:schema:validate
                  vendor/bin/console propel:schema:validate-xml-names

            - name: Validate transfer files
              run: vendor/bin/console transfer:validate

            - name: Run CodeStyle checks
              run: vendor/bin/console code:sniff:style

            - name: Run Architecture rules
              run: vendor/bin/phpmd src/ text vendor/spryker/architecture-sniffer/src/ruleset.xml --minimumpriority 2

            - name: Run PHPStan
              run: vendor/bin/phpstan analyze -l 5 -c phpstan.neon src/

            - name: Run Psalm
              run: vendor/bin/psalm.phar --show-info=false
